include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - generate_icon.dart
    - lib/src/game/logic/avondale_table.dart  # WIP: Has undefined types
    - lib/src/ui/widgets/bidding_dialog.dart  # WIP: Has undefined getters
    - lib/src/ui/widgets/bidding_panel.dart   # WIP: Has undefined types

linter:
  rules:
    require_trailing_commas: true
